version: '3.1'

services:
  backend:
    build: .
    command: python -m uvicorn main:app --host 0.0.0.0 --port 80
    ports:
      - '8080:80'
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASS: ${PG_PASS}
  postgresql:
      image: postgres
      restart: always
      ports:
          - 5432:5432
      environment:
          POSTGRES_DB: ${PG_DB}
          POSTGRES_USER: ${PG_USER}
          POSTGRES_PASSWORD: ${PG_PASS}
      volumes:
          - ./pgdata:/var/lib/postgresql/data
  pgadmin:
      image: dpage/pgadmin4
      environment:
          PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
          PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
          - 5050:80
      depends_on:
          - postgresql
